In [7]:
import torch
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):

    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


X = [
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
]

y = [0, 1, 0, 1, 0]

dataset = MyDataset(X, y)

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

In [8]:
for X_batch, y_batch in loader:
    print(X_batch)
    print(y_batch)

tensor([[1., 2.],
        [3., 4.]])
tensor([0, 1])
tensor([[ 9., 10.],
        [ 5.,  6.]])
tensor([0, 0])
tensor([[7., 8.]])
tensor([1])


# 📘 MODULE 14.3 — Dataset & DataLoader — Notes

![Image](https://images.openai.com/static-rsc-4/6qaA2pFHxFVKbnXRsoRoEsUVEIFnHhXzaAwAKM4MPLmYLJiXifrzCmfN1fD8oiubepvT78iRYT35vtjgCvHOJTai5Rg-LpHIWdODpWRbu1wRcIlbvYkuGSIplN_B7qVLOFV0ypMArndc1gPBQyeUT0CaIq1z0YcAV5ZidfppV_cSrJQ8qH1EU3ARLA11gsj3?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/Tm5Y834TLpO7hyTUry3M50iX3nAUq6JN6jmD0fJA8hFTmWAD6Hb94zfJBsOwhzPZJFDiisQVQwm1LMup4oHFZ8pSuwDObfLNT_WEScLWeETTR94zpnpaC1AmHanm6yOpUK3q_DloytQWhUdPS2bLMq5-wKV6DyNbkrB7zAUyy2VIgs2F0xFMCkcW-Q1xvThM?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/g34YDh_0rEJusi0MGBHOl6Vi81A9C48SH6qVKNsOLcbnZZp1hxeb7w1aM44ShRj-O-KUSMqRTue7k51GzXTVriG35qSdLr4okwXf6aNMKS9mbwi9AmabNP5SYJl6TPRVlieNq8N5fBRrmDJfa8GtiQMTxYwi9tR9goopxhksJOwTT0ONjATi_bIj3Q89ePRn?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/RTdZdZap6_0foaLApIst-3WPG3Rj-qe603_qzKkfttdGb5n3LARcCxr8FumsbJlR0ACxaZtXLUJBFw9WAzaLM5P2ipilEW1tOxGZ2bCgKUOeqgB1U-fZrbQbaO4ZKL1BmCk_8VelN_Tnz4NjHoeoc3niRclWkj9pwaYbCHzVhT1khRr_qWMmDavcgSi3868K?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/FX5q8uxK5lmlxpRpcWdXA06cySWkd_AOT6onKE6-wK53ZL-hLVp-wqevcSiTq-8Llw2FnCsa_T2RDQueRXYfaOTtHerjOJzZFUAceP1-aXrH4BAbH_0cP4uVvMu2d32UNWSJpyFzftk82TbxWI1_QESdrtr7vNwAt8hUhr4jSRKWqSmaQbWjcixxEQjM_R2E?purpose=fullsize)

> **Core idea:** `Dataset` defines **how individual samples are stored/accessed**, while `DataLoader` handles **iterating over those samples and organizing them into batches** for training.

---

# 1. 🔥🔥🔥 Dataset

PyTorch provides `torch.utils.data.Dataset` as the standard interface for representing datasets.

A dataset conceptually contains:

```text
Sample 0 → (x₀, y₀)
Sample 1 → (x₁, y₁)
Sample 2 → (x₂, y₂)
...
Sample N → (xₙ, yₙ)
```

For example:

```text
Image 0 → Cat
Image 1 → Dog
Image 2 → Cat
Image 3 → Dog
```

The Dataset's job is to provide access to these **individual samples**.

---

# 2. 🔥🔥 `__len__()` and `__getitem__()`

For a custom Dataset, two methods are fundamental.

### `__len__()`

Returns the number of samples.

```python
def __len__(self):
    return len(self.X)
```

### `__getitem__()`

Returns one sample.

```python
def __getitem__(self, index):
    return self.X[index], self.y[index]
```

Therefore:

```text
len(dataset)
     ↓
"How many samples?"

dataset[5]
     ↓
"Give me sample 5"
```

---

# 3. 🔥 Custom Dataset

Example:

```python
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]
```

Create it:

```python
dataset = MyDataset(X, y)
```

Access a sample:

```python
dataset[0]
```

Get dataset size:

```python
len(dataset)
```

---

# 4. 🔥🔥🔥 DataLoader

A `Dataset` provides individual samples.

A `DataLoader` provides those samples to the model, commonly **in batches**.

```python
from torch.utils.data import DataLoader

loader = DataLoader(
    dataset,
    batch_size=32
)
```

Conceptually:

```text
              Dataset
                 │
        ┌────────┼────────┐
        ▼        ▼        ▼
     Sample   Sample   Sample
        │        │        │
        └────────┼────────┘
                 ▼
             DataLoader
                 │
                 ▼
               Batch
                 │
                 ▼
               Model
```

---

# 5. 🔥 Dataset vs DataLoader

| Dataset                         | DataLoader                           |
| ------------------------------- | ------------------------------------ |
| Represents the data             | Iterates over the data               |
| Provides individual samples     | Provides batches                     |
| Implements `__len__()`          | Controls batching                    |
| Implements `__getitem__()`      | Can shuffle samples                  |
| Answers **"What is sample i?"** | Answers **"Give me the next batch"** |

### 🧠 Memory trick

> **Dataset = samples**

> **DataLoader = batches**

---

# 6. 🔥🔥 Batch Processing

Suppose:

$$
N=1000
$$

samples and:

$$
B=32
$$

batch size.

Instead of processing all 1000 samples simultaneously:

```text
1000 samples
     ↓
   Model
```

we process:

```text
Batch 1 → 32
Batch 2 → 32
Batch 3 → 32
...
Batch 32 → 32
Batch 33 → 8
```

Number of iterations:

$$
\text{steps per epoch}
=
\left\lceil\frac{N}{B}\right\rceil
$$

Therefore:

$$
\left\lceil\frac{1000}{32}\right\rceil
=
32
$$

So there are **32 batches/iterations per epoch**.

---

# 7. Why Batch Processing?

### ① Memory efficiency

The entire dataset doesn't have to pass through the model simultaneously.

### ② GPU efficiency

GPUs can perform operations on many samples in parallel.

### ③ Mini-batch gradient estimation

Each batch provides an estimate of the gradient:

$$
\nabla_\theta J_B
=
\frac{1}{B}
\sum_{i\in B}
\nabla_\theta L_i
$$

The optimizer then uses that gradient to update the parameters.

---

# 8. 🔥 `batch_size`

Example:

```python
loader = DataLoader(
    dataset,
    batch_size=32
)
```

means:

> Approximately 32 samples are provided at a time.

Training:

```python
for X_batch, y_batch in loader:

    prediction = model(X_batch)

    loss = loss_fn(prediction, y_batch)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
```

The model therefore sees:

```text
Batch
  ↓
Forward
  ↓
Loss
  ↓
Backward
  ↓
Update

Next Batch
  ↓
Forward
  ↓
Loss
  ↓
Backward
  ↓
Update
```

---

# 9. 🔥🔥 Shuffling

DataLoader can randomize sample order:

```python
loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True
)
```

Suppose the original order is:

```text
1 2 3 4 5 6 7 8
```

After shuffling:

```text
4 1 7 3 8 2 6 5
```

The **samples haven't changed**.

Only their order has changed.

A later epoch can use another order.

---

# 10. Why Shuffle?

Suppose the dataset is ordered:

```text
First 500 → Class A
Next 500  → Class B
```

Without shuffling, batches may contain highly structured groups of samples.

With:

```python
shuffle=True
```

the training examples are randomized before batching.

### Typical setup

```python
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)
```

The usual pattern is:

| Dataset    | Shuffle |
| ---------- | ------- |
| Training   | `True`  |
| Validation | `False` |
| Test       | `False` |

---

# 11. 🔥 DataLoader and Collation

DataLoader takes individual samples and organizes them into batches.

Suppose each sample has shape:

```text
(10)
```

Three samples:

```text
X₀ → (10)
X₁ → (10)
X₂ → (10)
```

A batch can become:

```text
X_batch → (3, 10)
```

Conceptually:

```text
Individual samples
       │
       │
       ▼
    Collation
       │
       ▼
     Batch
```

This process of combining individual samples into a batch is called **collation**.

For standard tensor samples, PyTorch's default behavior usually handles this automatically.

---

# 12. 🔥 Complete Custom Dataset + DataLoader

```python
import torch
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):

    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


X = [
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
]

y = [0, 1, 0, 1, 0]

dataset = MyDataset(X, y)

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)
```

Training/iteration:

```python
for X_batch, y_batch in loader:

    print(X_batch)
    print(y_batch)
```

With 5 samples and batch size 2:

$$
\left\lceil\frac{5}{2}\right\rceil=3
$$

So you'll get:

```text
Batch 1 → 2 samples
Batch 2 → 2 samples
Batch 3 → 1 sample
```

---

# 13. 🔥 Dataset → DataLoader → Model

This is the important architecture:

```text
                    DATA
                      │
                      ▼
                   Dataset
                      │
             __getitem__(index)
                      │
                      ▼
                 DataLoader
                      │
              Batch + Shuffle
                      │
                      ▼
                    Model
                      │
                      ▼
                 Prediction
                      │
                      ▼
                    Loss
                      │
                      ▼
                backward()
                      │
                      ▼
                 Optimizer
                      │
                      ▼
              Updated Model
```

This is the standard structure behind PyTorch training.

---

# 14. 🔥 Custom Datasets in Real Projects

The Dataset abstraction becomes particularly useful when data isn't already stored as tensors.

### Images

```text
Image file
    ↓
Read image
    ↓
Transform
    ↓
Tensor
    ↓
Label
```

### Tabular data

```text
CSV row
    ↓
Features
    ↓
Tensor
    ↓
Label
```

### Text

```text
Text
 ↓
Tokenization
 ↓
Token IDs
 ↓
Input + Target
```

### Audio

```text
Audio file
 ↓
Waveform
 ↓
Preprocessing
 ↓
Tensor
 ↓
Label
```

The interface remains:

```python
def __len__(self):
    ...

def __getitem__(self, index):
    ...
```

Only the internal data-loading logic changes.

---

# 15. 🔥 Dataset as an Abstraction

Think of a Dataset as providing two answers:

```text
PyTorch:
"How many samples are there?"
        ↓
      __len__()

PyTorch:
"Give me sample i."
        ↓
      __getitem__(i)
```

This makes different types of datasets compatible with the same PyTorch DataLoader and training pipeline.

---

# 16. 🔥 Batch Size Does NOT Change the Dataset

Suppose:

```python
len(dataset)
```

returns:

```text
1000
```

Changing:

```python
batch_size=32
```

to:

```python
batch_size=64
```

does **not** change the dataset.

The dataset still contains:

```text
1000 samples
```

Only the grouping changes:

```text
Dataset: 1000 samples

batch_size = 32
       ↓
~32 batches

batch_size = 64
       ↓
~16 batches
```

---

# 17. 🔥 Epoch vs Batch

Suppose:

$$
N=1000
$$

and:

$$
B=32
$$

Then:

$$
\text{steps per epoch}
=
\left\lceil\frac{1000}{32}\right\rceil
=
32
$$

Therefore:

```text
                 1 EPOCH
                    │
     ┌──────────────┼──────────────┐
     ↓              ↓              ↓
  Batch 1        Batch 2        Batch 3
     ...                           ...
                    ↓
                 Batch 32
                    │
                    ▼
              Epoch complete
```

An **epoch = one complete pass through the dataset**.

---

# 🧠 Final Comparison

| Term                | Meaning                                  |
| ------------------- | ---------------------------------------- |
| **Dataset**         | Represents/accesses individual samples   |
| **`__len__()`**     | Number of samples                        |
| **`__getitem__()`** | Retrieves one sample                     |
| **DataLoader**      | Iterates over the Dataset                |
| **Batch**           | Group of samples processed together      |
| **`batch_size`**    | Samples per batch                        |
| **`shuffle=True`**  | Randomizes training sample order         |
| **Epoch**           | One complete pass through dataset        |
| **Collation**       | Combines individual samples into a batch |

---

# 🔥 Final Cheat Sheet

```text
Dataset
  ↓
"Give me individual samples"

__len__()
  ↓
Number of samples

__getitem__(i)
  ↓
Sample i

DataLoader
  ↓
Organizes samples for iteration

batch_size
  ↓
How many samples per batch

shuffle
  ↓
Whether sample order is randomized

Batch
  ↓
Input group sent to model

Epoch
  ↓
One complete pass through dataset
```

### 🧠 One sentence to remember

> **`Dataset` defines how individual samples are accessed, while `DataLoader` efficiently iterates over those samples, groups them into batches, and optionally shuffles their order for training.**

---
