In [1]:
# Tensor Creation

In [2]:
import torch

x = torch.tensor([1,2,3])

print(x)

tensor([1, 2, 3])


In [3]:
print(x.shape)

torch.Size([3])


In [5]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
x = torch.randn(2,3)
print(x)

tensor([[-0.4102,  0.0547, -1.0845],
        [ 0.6880,  0.2231, -0.9830]])


In [9]:
x = torch.arange(0,10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
# 2) Indexing

In [11]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

In [12]:
x[0,1]

tensor(20)

In [13]:
x[:,1]

tensor([20, 50])

In [14]:
x[0,:]

tensor([10, 20, 30])

In [15]:
# 3)Slicing

In [16]:
x[:,0:2]

tensor([[10, 20],
        [40, 50]])

In [17]:
x = torch.arange(12)

In [18]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [21]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([10, 20, 30])

x + b

# in the background the PyTorch will do
# 10 20 30 
# 10 20 30

# so that b will be compatable with x in dimensions (2,3) + (2,3) = (2,3)

tensor([[11, 22, 33],
        [14, 25, 36]])

In [22]:
# Matrix Multiplication

In [23]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

C = A @ B

In [24]:
C

tensor([[19, 22],
        [43, 50]])

In [25]:
# for element wise operation

In [26]:
Elment_wise = A * B
Elment_wise

tensor([[ 5, 12],
        [21, 32]])

In [27]:
# Reduction operations

In [28]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

In [30]:
x.sum(dim = 0)
# column wise operation
# this will produce(3,)

tensor([5, 7, 9])

In [41]:
x.sum(dim=0, keepdim=True)
# it will produce (1,3)
# so it will make broadcast easier

tensor([[5, 7, 9]])

In [42]:
# stacking

In [47]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

y = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

torch.cat([A, B], dim=1).shape

torch.Size([2, 4])

In [48]:
torch.stack([A, B], dim=1).shape

torch.Size([2, 2, 2])

## 13.2 Tensor Operations — Revision Notes

> **Core idea:** Tensor operations are the basic building blocks used to manipulate data before, during, and after neural-network computation.

![Image](https://images.openai.com/static-rsc-4/jP6T4_-zY6eGYsYAEkj-gbHgv29gWRBRhGv2iwqC880-ZvpsMM2D51G56Ozqm6pXmOnW0AwaUcR5FcXeURoHfMwcpp4CJuw_3T9XgUy8Uo1J3e5Jm_fwaD1BotDO4kw3nHlqfkjQNUZJ8Jkwo5QRkVyf49vgtn4z-MnQhjw68hnr7BlRc2Qf60gacJ-O4k2C?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/mj_aHbnlw02cz1MmigkcM3QeZfS2D29MFa31yPtCI6zTiobp8mk58CWMHM5Ff6QtJyI70KHQD8No23IbA9fF7kNlXuo3-jGFDMCdaqDw6ZvY9tGxdsNTMIYfBYNJnbeI2Av9fs0lU4ON7IRk61u8xqUQLpzcEq8AFQQ6yWzhrCbjw18LNh7RC7uZHVxMuu39?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/Uax5T9R3KeO8PBHZelr8BSvn_YRgIGT4xSnRwE_2TFjSKvPi8g4fi5cTOLSm_nCUKTJlj0p5QpqyFOlWJPSFQili1M3Sn19lAzjPc9KV2oIR7VYfp0wOiG_Kqe4vIhu_b3feZmd_rgYYSeXnTUg6WsBSV_lI_GcH3RFu-PZ-dhX0bH-0H1XwezPScXOrj2lA?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/y2cjdQetytbk7PyNkdIFHy6dY_t4GVAtCTsujUOG4i_hOJmkvCXHugIiJXTNAqOq0jxjIh5CMC-27UH7oLJvBvCYVPGyCyS0RBIHZ9AmzqD7wjrxqnvQaPtQOj38zGyyIkvZ0JCB9xQ0Q2tcC6v2OuQlxY6apxe9h8NCDkIPX40_nhb6PQ7m0W0AdVJn_IyZ?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/-XRy-VVpX1CCq4WIwcvPFWueWrX94xXFYroE2nGWSpPu6rhxFQLro3fJ_wVwVxFPBjGZk4d6ih7DiL5IybTiZ0bKwGGAKXemC4uCjSXMA2WZtqQKB8lUWlWEQjzunJOH_Mw8c9_yl2pZ1vr0bihC3DWI-nctGmEK24OUT63n8Zq2Z1tk-KVUt6-iRZBKkTrG?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/jmgwua5fhAE5RXPs4FnmbJTbm8qmTYes0LlD5n6XULeN5W5vVmcKxCKmVBzbm5bTqJ30-SxNl7NN0RMOhJ6IdVP6aN8wsQamRje_kk6X7EJ2qahFNv7Z8EDLB9h3K1DZ8rNABFr9AToQdjw49uXzBOrNz1Jw-7VIGJ6F0K_D_eiYrCN4YsDahoBfYF5fcM86?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/ps_4xxfH34_ugM2DvZQAHRqH5nowC-YNbxlTtRrC-kKkMwXEWoRC94z0j4RehiTarcPjO2xjsIF-VraUbtpnpASfMCFujfYayH_p0d7uNQUIZtmm7PrPTMtOrtm_VdPDJJyT9uoidWXYeqt8e_6k4wru5aYwIA7CZV_5TRXgJkCqy-HoqVAj7_3t2KcDbgD4?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/JQ2e27IqEly6rlhB3pZCCcOpZ4UFjWBHVA978CVhnvlwLWpruEgb4iyF4vjKEFFI1ve67tao0vuLJQc9MHWRINgz7a1eGU_VvDQiNOxC2MUz6uF1g4KOj1V2J0PTPz4MOaXne9o-91I5OwUuygY9CkA9FCvuMKf8um5HEtmd2WnCIzZoZKtPSHfJrUicjjz8?purpose=fullsize)

---

# 1. 🔥 Tensor Creation

PyTorch provides several ways to create tensors.

### From existing data

```python
x = torch.tensor([1, 2, 3])
```

### Zeros

```python
x = torch.zeros(2, 3)
```

### Ones

```python
x = torch.ones(2, 3)
```

### Random values

```python
x = torch.randn(2, 3)
```

### Sequence

```python
x = torch.arange(0, 10)
```

### Important

You should also be aware of:

```python
x.dtype
x.shape
x.device
```

because tensor operations depend heavily on **shape, dtype, and device**.

---

# 2. 🔥 Indexing & Slicing

Consider:

```python
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])
```

Shape:

$$
(2,3)
$$

### Single element

```python
x[0, 1]
```

→ `20`

### Row

```python
x[0]
```

→ `[10, 20, 30]`

### Column

```python
x[:, 1]
```

→ `[20, 50]`

### Slice

```python
x[:, 0:2]
```

→

```text
[[10, 20],
 [40, 50]]
```

### 🧠 Remember

```text
x[row, column]
```

PyTorch uses **zero-based indexing**.

---

# 3. 🔥 Reshaping

Reshaping changes the tensor's shape while preserving its number of elements.

```python
x = torch.arange(12)

x = x.reshape(3, 4)
```

Before:

$$
(12)
$$

After:

$$
(3,4)
$$

because:

$$
12=3\times4
$$

### Fundamental rule

$$
\boxed{
\text{elements before}
=
\text{elements after}
}
$$

So:

```text
(2,3,4) → (4,6)
```

is valid because:

$$
2\times3\times4=4\times6=24
$$

but:

```text
(2,3,4) → (5,5)
```

is invalid because:

$$
24\neq25
$$

---

## `-1`

PyTorch can infer one dimension:

```python
x.reshape(3, -1)
```

For 12 elements:

$$
3\times?=12
$$

therefore:

$$
?=4
$$

Result:

```text
(3,4)
```

### Memory trick

> **Reshape changes organization, not the number of elements.**

---

# 4. 🔥 Broadcasting

Broadcasting allows operations between tensors with compatible shapes.

Example:

```python
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([10, 20, 30])

x + b
```

Conceptually:

```text
1  2  3       10 20 30
4  5  6   +   10 20 30
-----------------------
11 22 33
14 25 36
```

![Image](https://images.openai.com/static-rsc-4/7QkOgpu9-X4mQnQkIxbDsUv7LQ2DinkVtg7Gu1-DURkzmfkm2cMxOXyV3O3SLcWDYNq-DgCuWAje11zel4X0EnmL2uRrDYmFX1EqRqHUUVzpeSe9GJQiKWU4W_J10zv9Y1swammc2ebP82UUAjSvi2CO5_I7xegAUGVuPRHtIvnVdMg3p-oAIZiBgvTL0Sw8?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/iPIDaF5VWIbXcqz8TsE1U2sMArfC32Enkv7AwP2qZ8km0qP3YQG1WBhsjjwdW7DnopsRVU8cSU94zBuHO8hOAT8r2GokD3ZJsk5wgj7AiU6DoPfb7j-NRiZhmQ6t7tlCZrzoj1JtK_GBLb_7YwLMgRqrL6Rh_psNqfSSFIeEg2RTwK0RxazYyXjaMrvkkzT3?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/n25AewysHrNzDOt_X04lGtrDoXkAEUEMEcu7xMkORN4ooflFl064F1xZWuARAnVgwl-IlJsJBtLe64qKTQVjawNqAcHQXE-_2cqBl92cpwmyre9P8AlCWTlzz-NLvZPkGM6yQaXbLFGShOChGLyis-gLcJ2BOcqIQe-yjN_0Z-W6mT73X4P0FpnY1dTwfoSO?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/CeLQ8164DJ6087oK3nWo7onYBnXe-104yAgNRog3tHlOMvwqhcbTFEGc8oZlJTuhW27ZUiLu1nGE6pm7XZw8Ct6TC_IFlcojIxV3xjBVB0rW7rX192laN0xyHkIJbJ5EFe134EFdlehhUKlqsGkaOEpo3FovfOSTTL0Jwn7izpuxop0UTeYAGFmh04KVuxMY?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/g0A9Igbb2MVi_iugXfgexgt4qYUCe3y2KcdLfCyOzsCvR6pb-bonzjSPCd008M90GEGd4vZpWLi5hImepY7dq_4nBgiUGphN1ZH9P2jKY5_RJs0wADV2vdZ5w29SBm9sEV_yWDjYsJ4xMw_hlJ67509AxJMem2mrFiz31YKMCUcDMhoWqtlBMvqORfjMau_2?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/cAP-VFOVvtZI9JAwO2Ht2XX6aVnAxmKbfCoc6lofVwBU4_VVr0oNLisSh9aDuh9j5f7cfu64ufPT6pSw3Ow40SAMl01n2XTjlujkeEQoD4CIOocWoZrk7ZyEg0dHULKyNwytAXkKJ7uW8t5DeY3eQghzCvMdFgWj1QuHR5AzK6p652QcDx1IaeA6HIJZsvCX?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/PZKowuCbwNqB-Lbf_dC7NqRAm6dzveDv9PI5SX2yKl94_3QbBsrzpBrncAeGs0KoLNzNsjF4A5ngPUFPGoIbld_9cWmQKGT6xqI6bI-Ucg1eWMZFZA1teUo6OgXNo4QcEya4oAAOOA3GSp-W1cD-5BgFb0GoQwdRitAfWdn7s8lj9BEzdIfc5lHYtNExEFMg?purpose=fullsize)

---

## 🔥 Broadcasting rules

Compare dimensions **from right to left**.

Two dimensions are compatible when:

1. They are equal, or
2. One is `1`, or
3. One dimension is missing.

Example:

```text
(2,3)
(3,)
```

Align:

```text
(2,3)
   (3)
```

Compatible → ✅

Another:

```text
(4,3,2)
(1,2)
```

Align:

```text
(4,3,2)
    (1,2)
```

Compatible → ✅

But:

```text
(2,3)
(2,)
```

aligns as:

```text
(2,3)
   (2)
```

`3` and `2` don't match → ❌

---

# 5. 🔥 Broadcasting in Neural Networks

This is particularly important for:

$$
Z=WX+b
$$

Suppose:

```text
Z.shape = (32,10)
b.shape = (10,)
```

PyTorch can broadcast the bias across all 32 samples:

$$
(32,10)+(10)
\rightarrow
(32,10)
$$

So one bias vector can be applied to every sample.

> **Broadcasting is one reason tensor operations can closely match the mathematical notation used in neural networks.**

---

# 6. 🔥 Matrix Multiplication

For:

$$
A\in\mathbb{R}^{m\times n}
$$

and:

$$
B\in\mathbb{R}^{n\times p}
$$

the result is:

$$
AB\in\mathbb{R}^{m\times p}
$$

Shape rule:

```text
(m,n) × (n,p)
      ↓
    (m,p)
```

The **inner dimensions must match**.

---

## PyTorch

```python
C = A @ B
```

or:

```python
C = torch.matmul(A, B)
```

Example:

```python
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

C = A @ B
```

Result:

```text
[[19, 22],
 [43, 50]]
```

For example:

$$
1(5)+2(7)=19
$$

---

# 7. 🚨 `*` vs `@`

Very important:

### `*` → element-wise multiplication

```python
A * B
```

Each corresponding element is multiplied.

### `@` → matrix multiplication

```python
A @ B
```

Uses matrix multiplication rules.

```text
*  → element by element

@  → linear algebra matrix multiplication
```

---

# 8. 🔥 Why Matrix Multiplication Matters

A fully connected neural-network layer uses:

$$
Z=WX+b
$$

The core operation is:

$$
WX
$$

So matrix multiplication appears throughout Deep Learning.

```text
Input
  ↓
Matrix multiplication
  ↓
Bias
  ↓
Activation
  ↓
Output
```

---

# 9. 🔥 Reduction Operations

A reduction combines many values into fewer values.

Common operations:

```python
x.sum()
x.mean()
x.max()
x.min()
```

For:

```text
1  2  3
4  5  6
```

### Sum

$$
1+2+3+4+5+6=21
$$

```python
x.sum()
```

### Mean

$$
\frac{21}{6}=3.5
$$

```python
x.mean()
```

### Maximum

```python
x.max()
```

→ `6`

---

# 10. 🔥 Reduction Along a Dimension

Suppose:

```python
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
```

### `dim=0`

```python
x.sum(dim=0)
```

Result:

```text
[5, 7, 9]
```

because:

$$
1+4=5
$$

$$
2+5=7
$$

$$
3+6=9
$$

---

### `dim=1`

```python
x.sum(dim=1)
```

Result:

```text
[6, 15]
```

because:

$$
1+2+3=6
$$

$$
4+5+6=15
$$

---

# 11. 🔥 `keepdim=True`

Normally:

```python
x.sum(dim=1)
```

might transform:

```text
(2,3)
```

into:

```text
(2,)
```

With:

```python
x.sum(dim=1, keepdim=True)
```

the result is:

```text
(2,1)
```

This is particularly useful when the reduced result will later participate in **broadcasting**.

---

# 12. 🔥 Concatenation — `torch.cat()`

Concatenation joins tensors along an **existing dimension**.

Suppose:

```text
A.shape = (2,3)
B.shape = (2,3)
```

### Along `dim=0`

```python
torch.cat([A, B], dim=0)
```

Result:

$$
(4,3)
$$

### Along `dim=1`

```python
torch.cat([A, B], dim=1)
```

Result:

$$
(2,6)
$$

![Image](https://images.openai.com/static-rsc-4/x01bSpuYZq6kuMiB72Cxf6JUS3EwlgQdlwMGkVEaVeod1c6BINy8aCxmrWiT9feVaSyd21DXUa6TFCfd4mTuVGOACQdCOqKA-StaHJmidwdmE5JOpUqLvyQCDaH0EppROo8FoyZrCWk6JFLMPxRrD_O8ZprECNDHGwpEa1YmEAFxKwOhvTKgPkyx3GaOgcdI?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/D_z_NnYVEcUao_V55hffMic-UPEjSN02wxZn6sOJJl5_-WjA7zrMyZ9D7-aRgN7HUnz732G-6HNbTWkUb9CoCMqNTxPFGA7bJXXMcwrWIFN6GSDUiuDq-siDVTUSIRo14RCnGSVVPAuB5XQL6ziHnceELTPjdIE2jv-qnFub_OjusqW0w-giz_MfXJBTDnN2?purpose=fullsize)

![Image](https://images.openai.com/static-rsc-4/U-Ff9lrBkwjvhhO1cU_KgDlrRwc9zrLm7JjSfgbgyuW5CsuS6eqOeEnn8hziGGWZkU1vxwNMnQPYpdQkE3R-DgNlTv7t-jF6RfatE3b-Yvad_oTkx4sEcrC3s2DvP2AY_MLrdroSuXiMv40t-Rq_xWfZrWu76SdqX09VO0NnWyrTvu-FK9na9KORGSbN5Fxy?purpose=fullsize)

---

## Concatenation rule

All dimensions must match **except the dimension being concatenated**.

Example:

```text
A = (2,3)
B = (4,3)
```

Along `dim=0`:

```text
(2,3)
(4,3)
 ↓
(6,3)
```

✅

Along `dim=1`:

```text
(2,3)
(4,3)
```

First dimensions don't match:

$$
2\neq4
$$

❌

---

# 13. 🔥 Stacking — `torch.stack()`

Stacking combines tensors by creating a **new dimension**.

Suppose:

```text
A = (2,3)
B = (2,3)
```

### `cat`

```python
torch.cat([A, B], dim=0)
```

→

```text
(4,3)
```

### `stack`

```python
torch.stack([A, B], dim=0)
```

→

```text
(2,2,3)
```

So:

$$
\boxed{\text{cat → existing dimension}}
$$

$$
\boxed{\text{stack → new dimension}}
$$

---

# 14. 🔥 `cat()` vs `stack()`

|                           | `torch.cat()` | `torch.stack()` |
| ------------------------- | ------------- | --------------- |
| Creates new dimension?    | ❌             | ✅               |
| Joins existing dimension? | ✅             | ❌               |
| Example input             | `(2,3)+(2,3)` | `(2,3)+(2,3)`   |
| Example output            | `(4,3)`       | `(2,2,3)`       |

### 🧠 Memory trick

> **CAT = concatenate into an existing axis.**

> **STACK = stack into a new axis.**

---

# 15. 🧠 Real Deep Learning Examples

### Combining batches

```text
batch1 = (32,10)
batch2 = (16,10)
```

```python
combined = torch.cat(
    [batch1, batch2],
    dim=0
)
```

Result:

$$
(48,10)
$$

You're adding more **samples**.

---

### Creating a batch dimension

Suppose:

```text
sample = (10,)
```

Two samples:

```python
batch = torch.stack(
    [sample1, sample2],
    dim=0
)
```

Result:

$$
(2,10)
$$

You're creating a new **batch dimension**.

---

# 16. 🔥 Operation → Shape Mental Model

This is the most important revision table:

| Operation    | What happens to data?   | Shape effect                 |
| ------------ | ----------------------- | ---------------------------- |
| Indexing     | Select values           | Usually reduces/selects axes |
| Slicing      | Select range            | Selects part of tensor       |
| Reshape      | Rearrange shape         | Same number of elements      |
| Broadcasting | Align compatible shapes | Implicit expansion           |
| `@`          | Matrix multiplication   | `(m,n)×(n,p) → (m,p)`        |
| `sum()`      | Combine values          | Reduces dimensions           |
| `mean()`     | Average values          | Reduces dimensions           |
| `cat()`      | Join tensors            | Existing dimension grows     |
| `stack()`    | Group tensors           | New dimension appears        |

---

# 17. ⚠️ Common Mistakes

### ❌ Reshaping to an incompatible number of elements

```text
(12) → (5,5)
```

❌ because:

$$
12\neq25
$$

---

### ❌ Confusing `*` and `@`

```python
A * B
```

≠

```python
A @ B
```

---

### ❌ Forgetting broadcasting rules

```text
(2,3) + (2,)
```

❌ because the aligned dimensions are `3` and `2`.

---

### ❌ Confusing `cat` and `stack`

```text
cat   → existing dimension
stack → new dimension
```

---

### ❌ Forgetting `dim`

```python
x.sum()
```

and:

```python
x.sum(dim=0)
```

do **different reductions**.

---

# 🎯 Interview / GATE-Style Points

### Q1. What must remain constant during reshape?

The total number of elements.

$$
\boxed{\prod \text{old dimensions}
=
\prod \text{new dimensions}}
$$

### Q2. What is broadcasting?

Automatic alignment/expansion of compatible tensor dimensions during operations.

### Q3. What are the matrix multiplication shape requirements?

For:

$$
(m,n)(n,p)
$$

the inner dimensions must match.

### Q4. Difference between `*` and `@`?

```text
* → element-wise multiplication
@ → matrix multiplication
```

### Q5. Difference between `cat` and `stack`?

```text
cat   → existing dimension
stack → new dimension
```

### Q6. What does `dim=0` mean?

The first axis/dimension.

### Q7. What does `keepdim=True` do?

It retains the reduced dimension with size `1`.

---

# 🚀 Final Cheat Sheet

```text
CREATION
torch.tensor()
torch.zeros()
torch.ones()
torch.randn()
torch.arange()

INDEXING
x[i]
x[i,j]
x[:,j]
x[a:b]

RESHAPING
x.reshape(...)
→ same number of elements

BROADCASTING
compatible shapes
→ automatic expansion

MATRIX MULTIPLICATION
A @ B
(m,n) × (n,p)
→ (m,p)

REDUCTION
sum()
mean()
max()
min()
→ fewer values / dimensions

CONCATENATION
torch.cat()
→ existing dimension

STACKING
torch.stack()
→ new dimension
```

## 🧠 Ultimate memory trick

> **Index to select → reshape to reorganize → broadcast to align → `@` to multiply → reduce to summarize → `cat` to join → `stack` to create a new axis.**

---
